version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: about_me
    restart: unless-stopped
    network_mode: host
    command: node ./.output/server/index.mjs --color
    volumes:
      - ./.output:/app/.output